Repository hmcts/div-document-generator-client, pull requests merged in 2019-09, with the labels that each got.

#196 DIV-5701 Amend mini-petition PDF to exclude resp/co-resp addresses if confidential
  dependency-check-suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/PDFGenerationTest.java
  src/integrationTest/resources/documentgenerator/documents/jsoninput/mini-petition-draft-resp-confidential-addr.json
  src/integrationTest/resources/documentgenerator/documents/jsoninput/mini-petition-resp-confidential-addr.json
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/mini-petition-draft-resp-confidential-addr.pdf
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/mini-petition-resp-confidential-addr.pdf
  src/main/resources/data/templates/divorcedraftminipetition.html
  src/main/resources/data/templates/divorceminipetition.html
Labels: ns:div-dgs-pr-196

#198 Fix vulnerabilities
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:div-dgs-pr-198

#189 DIV-5098 Add DN Refusal Order Docmosis Document
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/EMStoreIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/PDFGenerationTest.java
  src/integrationTest/resources/documentgenerator/documents/jsoninput/decree-nisi-refusal-order-clarification.json
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/decree-nisi-refusal-order-clarification.pdf
  src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/domain/TemplateConstants.java
  src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/TemplateDataMapper.java
  src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/DocumentManagementServiceImpl.java
  src/main/resources/application.yml
  src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/functionaltest/DocumentGenerateAndStoreE2ETest.java
  src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/TemplateDataMapperTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/service/impl/DocumentManagementServiceImplUTest.java
Labels: ns:div-dgs-pr-189

#193 DIV-3877 - enable respondent solicitor feature in AAT
  Jenkinsfile_CNP
  charts/div-dgs/values.aat.template.yaml
  charts/div-dgs/values.preview.template.yaml
  infrastructure/aat.tfvars
  src/integrationTest/resources/application.properties
  src/integrationTest/resources/example-application-local.properties
Labels: ns:div-dgs-pr-193

#199 Remove contact details formatting
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Offline-Invitation-Letter-Respondent.pdf
  src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/domain/TemplateConstants.java
  src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/TemplateDataMapper.java
  src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/mapper/TemplateDataMapperTest.java
Labels: ns:div-dgs-pr-199

#200 Use hmcts/cnp module
  infrastructure/main.tf
Labels: ns:div-dgs-pr-200

#201 DIV-5762 - use java chart v2.6.0 and reduced duplicated env references
  charts/div-dgs/Chart.yaml
  charts/div-dgs/requirements.yaml
  charts/div-dgs/values.aat.template.yaml
  charts/div-dgs/values.preview.template.yaml
  charts/div-dgs/values.yaml
Labels: ns:div-dgs-pr-201

#202 DIV-5762 - added disableLegacyDeployment() to Jenkinsfile_CNP
  Jenkinsfile_CNP
Labels: ns:div-dgs-pr-202

#204 DIV-5781: Address Jackson Databind vulnerabilities (CVE-2019-14540 and 16335)
  dependency-check-suppressions.xml
Labels: ns:div-dgs-pr-204

#203 Delete application from ASE
  infrastructure/main.tf
Labels: ns:div-dgs-pr-203

#207 cleanup ASEs
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
Labels: ns:div-dgs-pr-207

#208 DIV-5839 - fixed incorrect instructions on AOS solicitor template
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Solicitor.pdf
  src/main/resources/application.yml
  src/main/resources/data/templates/aosinvitation.html
Labels: ns:div-dgs-pr-208

#209 DIV-5839 - added missing vault_env
  infrastructure/variables.tf
Labels: ns:div-dgs-pr-209
