Repository hmcts/div-document-generator-client, pull requests merged in 2021-01, with the labels that each got.

#408 CVE-2020-8908
  build.gradle
Labels: ns:divorce, prd:div, rel:div-dgs-pr-408

#411 RPET-655: update nightly build steps
  Jenkinsfile_nightly
  security.sh
Labels: ns:divorce, prd:div, rel:div-dgs-pr-411

#412 Trimmed down dependency checks supressions
  dependency-check-suppressions.xml
Labels: ns:divorce, prd:div, rel:div-dgs-pr-412

#413 DGS build issue Investigation
  build.gradle
Labels: ns:divorce, prd:div, rel:div-dgs-pr-413
