Repository hmcts/div-document-generator-client, pull requests merged in 2021-11, with the labels that each got.

#447 RPET-741: changing AOS template text from 7 days to 7 working days
  README.md
  build.gradle
  charts/div-dgs/Chart.yaml
  docker-compose.yml
  gradle/wrapper/gradle-wrapper.properties
  src/contractTest/java/uk/gov/hmcts/reform/divorce/documentgenerator/PdfGGenerationServiceConsumerTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/IdamUtils.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/IntegrationTest.java
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Amend_Petition-Sol-Online-Avl.pdf
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Amend_Petition.pdf
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Co-respondent_Online.pdf
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Co-respondent_Paper.pdf
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Hus_Res-Addr_DivUnit-EM-Sol-Online-Avl.pdf
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Hus_Res-Addr_DivUnit-EM.pdf
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Hus_Res-Addr_DivUnit-SC-Sol-Online-Avl.pdf
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Hus_Res-Addr_DivUnit-SC.pdf
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Offline-2-Year-Separation-Form.pdf
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Offline-5-Year-Separation-Form.pdf
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Offline-Adultery-Form-Co-Respondent.pdf
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Offline-Adultery-Form-Respondent.pdf
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Offline-Behaviour-Desertion-Form.pdf
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Offline-Invitation-Letter-Co-Respondent.pdf
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Offline-Invitation-Letter-Respondent.pdf
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Online-rep-resp-journey.pdf
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Same-Sex-Female-Sol-Online-Avl.pdf
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Same-Sex-Female.pdf
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Same-Sex-Male-Sol-Online-Avl.pdf
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Same-Sex-Male.pdf
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Solicitor-rep-resp-journey.pdf
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Solicitor.pdf
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Wife_Sol-Addr_DivUnit-SW_No-Sol-Company.pdf
  src/integrationTest/resources/documentgenerator/documents/pdfoutput/AOS_Wife_Sol-Addr_DivUnit-WM.pdf
  src/main/resources/data/templates/aosinvitation-rep-resp-journey.html
  src/main/resources/data/templates/aosinvitation.html
  src/main/resources/data/templates/co-respondentinvitation.html
Labels: ns:divorce, prd:div, rel:div-dgs-pr-447

#512 Suppress CVEs
  README.md
  dependency-check-suppressions.xml
Labels: ns:divorce, prd:div, rel:div-dgs-pr-512

#513 upgrade gradle 7.2
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:divorce, prd:div, rel:div-dgs-pr-513

#517 DFR-465: fortify integration
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:divorce, prd:div, rel:div-dgs-pr-517
