Repository hmcts/div-document-generator-client, pull requests merged in 2022-08, with the labels that each got.

#578 DFR-1086 Update Readme
  README.md
Labels: ns:divorce, prd:div, rel:div-dgs-pr-578

#581 Add backstage configuration file
  catalog-info.yaml
Labels: ns:divorce, prd:div, rel:div-dgs-pr-581

#583 comment out failing functional/smoke tests
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/IntegrationTest.java
  src/integrationTest/resources/application.properties
Labels: ns:divorce, prd:div, rel:div-dgs-pr-583
