Repository hmcts/div-document-generator-client, pull requests merged in 2025-06, with the labels that each got.

#659 DFR-3799 Bump Fortify
  Dockerfile
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  README.md
  build.gradle
  charts/div-dgs/Chart.yaml
  charts/div-dgs/values.yaml
  config/checkstyle/checkstyle.xml
  dependency-check-suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  lib/AI-Agent.xml
  lib/applicationinsights.json
  src/integrationTest/resources/application.properties
  src/integrationTest/resources/example-application-local.properties
  src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/config/HttpConnectionConfiguration.java
  src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/controller/DocumentGenerateDownloadController.java
  src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/controller/DocumentGeneratorController.java
  src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/domain/request/GenerateDocumentRequest.java
  src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/management/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/divorce/documentgenerator/management/test/endpoint/DocumentDownloadTestController.java
  src/main/resources/application.yml
  src/main/resources/bootstrap.yaml
  src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/config/TemplatesConfigurationTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/functionaltest/DocumentGenerateAndStoreE2ETest.java
  src/test/java/uk/gov/hmcts/reform/divorce/documentgenerator/management/monitoring/health/HealthCheckITest.java
Labels: ns:divorce, prd:div, rel:div-dgs-pr-659

#665 Suppress CVE-2025-48734
  dependency-check-suppressions.xml
Labels: ns:divorce, prd:div, rel:div-dgs-pr-665

#682 Delete dependabot
  .github/dependabot.yml
Labels: ns:divorce, prd:div, rel:div-dgs-pr-682
